### ISSUE TITLE
MainNetcdfDFSMCC breaks when calling rows() on non 2d matrix

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#120]
When running MainNetcdfDFSMCC you will get the following error :
16/08/15 19:05:56 ERROR Executor: Exception in task 0.0 in stage 8.0 (TID 39)
java.lang.IllegalStateException: Unable to get number of of rows for a non 2d matrix
        at org.nd4j.linalg.api.ndarray.BaseNDArray.rows(BaseNDArray.java:3591)
        at org.dia.tensors.Nd4jTensor.rows(Nd4jTensor.scala:147)
        at org.dia.algorithms.mcc.MCCOps$.labelConnectedComponents(MCCOps.scala:149)

The problem is that the merg files have arrays of shape (1, 4125, 1238).
Calling rows on a 3d array yields an error.
We need to reshape this array to (4125, 1238).
This does not change how the elements are organized we're just getting
rid of a dimension in the shape.

@kwhitehall Thoughts?

**Comment by rahulpalamuttam** [comment]
closing this issue as the fix is in.
