### ISSUE TITLE
sbt -run gives us a classNotFound exception on scala.Some

### ISSUE THREAD

**Issue by rahulpalamuttam** [SciSpark/SciSpark#54]
Running sbt run results in the error pasted below.

While I am not completely clear what the issue is - it is most likely due to the fact
that different packages are being compiled under different scala versions.

We have the base scala version set at 2.10.4, however there is a dependency
that forces sbt to use 2.10.6, and it is most likely due to the newer version of ND4S pulling from 0.4-rc3.8. Again not sure exactly how or why the compiler doesn't just use 2.10.6 for all dependencies once it detects that it ends it. 

The fix is to change the default scala version to 2.10.6.
Will submit a pull-request shortly.

ERROR :

java.io.IOException: java.lang.ClassNotFoundException: scala.Some
        at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1207)
        at org.apache.spark.Accumulable.readObject(Accumulators.scala:151)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1898)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:115)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:193)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.Some

**Comment by rahulpalamuttam** [comment]
PR #55

**Comment by kwhitehall** [comment]
Issue address in PR #55
