### ISSUE TITLE
Investigate why NetcdfDataset is returning SSL error

### ISSUE THREAD

**Issue by kwhitehall** [SciSpark/SciSpark#69]
This is most likely due to HTTPclient jar conflicts. 

The error is given below:
java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V
    at ucar.httpservices.HTTPSession.setGlobalSSLAuth(HTTPSession.java:721)
    at ucar.httpservices.HTTPSession.processDFlags(HTTPSession.java:442)
    at ucar.httpservices.HTTPSession.<clinit>(HTTPSession.java:408)
    at ucar.httpservices.HTTPFactory.newSession(HTTPFactory.java:57)
    at ucar.httpservices.HTTPMethod.<init>(HTTPMethod.java:220)
    at ucar.httpservices.HTTPMethod.<init>(HTTPMethod.java:194)
    at ucar.httpservices.HTTPFactory.Get(HTTPFactory.java:127)
    at ucar.nc2.dataset.NetcdfDataset.checkIfDods(NetcdfDataset.java:862)
    at ucar.nc2.dataset.NetcdfDataset.disambiguateHttp(NetcdfDataset.java:820)
    at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:706)
    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:427)
    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:410)
    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:395)
    at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:382)
    at $iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:42)

**Comment by kwhitehall** [comment]
Hi @rahulpalamuttam, as we've been looking at this the last couple of days, I thought it prudent to document here. Feel free to update.

**Comment by rahulpalamuttam** [comment]
The first issue we were tackling is that the openDap dependency needed to be updated otherwise we get the following error when trying to use the netcdf api:

java.io.IOException: opendap.jar is not on classpath or is incorrect version
    at ucar.nc2.dataset.NetcdfDataset.openDodsByReflection(NetcdfDataset.java:1027)
    at ucar.nc2.dataset.NetcdfDataset.acquireDODS(NetcdfDataset.java:983)
    at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:711)

Updating the dependency to use 4.6.6 gives us the versioning issue, which is due to the wrong http client being loaded. The httpClient dependency conflict is due to the fact that spark also httpClient.

A quick fix that I've found is to not use the latest open dap version (4.6.6), but rather a not so recent version (4.6.0). This does not solve the underlying issue with 4.6.6 but rather avoids it by using 4.6.0. For the sake of the conference I think the PR should be merged once tested. I still don't have access to the SciSpark cluster.
@kwhitehall.

**Comment by kwhitehall** [comment]
Thanks @rahulpalamuttam!  All is well

**Comment by kwhitehall** [comment]
This issue is fixed in PR #70
